server:
  port: 8085
db:
  port: 3306
  name: developer_internship_new
  endpoint: localhost
  username: root
  password: Passw0rd

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.endpoint}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}

  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


url:
  redirect:
    path: ${domain.path}
domain:
  path: http://localhost:3000/
