-- 1. Bảng University_Type
INSERT
IGNORE INTO `university_type`(created_by_user_id, created_date, last_modified_by_user_id, last_modified_date,
                                     name)
VALUES (NULL, NOW(), NULL, NOW(), 'Đại Học'),
       (NULL, NOW(), NULL, NOW(), 'Cao Đẳng'),
       (NULL, NOW(), NULL, NOW(), 'Trung Cấp');

-- 2. Bảng University
INSERT
IGNORE INTO `university` (created_by_user_id, created_date, last_modified_by_user_id, last_modified_date,
                                 avatar, description, email, location, name, phone, short_name, website,
                                 status_id, university_type_id)
VALUES (NULL, NOW(), NULL, NOW(), NULL, NULL, 'info@hust.edu.vn', 'Hà Nội', 'Đại học Bách Khoa Hà Nội',
        '024-3869-3000', 'HUST', 'http://www.hust.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'info@usth.edu.vn', 'Hà Nội',
        'Đại học Công nghệ - Đại học Quốc gia Hà Nội', '024-3754-5749', 'USTH', 'http://www.usth.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'contact@fpt.edu.vn', 'Hà Nội', 'Đại học FPT', '024-7300-2211',
        'FPTU', 'http://www.fpt.edu.vn', 1, 2),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'info@hcmus.edu.vn', 'TP.HCM',
        'Đại học KHTN - Đại học Quốc gia TP.HCM', '028-3822-2999', 'HCMUS', 'http://www.hcmus.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'contact@ftu.edu.vn', 'Hà Nội',
        'Đại học Ngoại thương Hà Nội (chuyên ngành IT)', '024-3768-1399', 'FTU', 'http://www.ftu.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'info@hcmut.edu.vn', 'TP.HCM', 'Đại học Bách Khoa TP.HCM',
        '028-3722-0271', 'HCMUT', 'http://www.hcmut.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'contact@hcmue.edu.vn', 'TP.HCM',
        'Đại học Sư phạm Kỹ thuật TP.HCM', '028-3822-2453', 'HCMUE', 'http://www.hcmue.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'info@hutech.edu.vn', 'TP.HCM', 'Đại học HUTECH', '028-3722-2661',
        'HUTECH', 'http://www.hutech.edu.vn', 1, 2),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'info@uit.edu.vn', 'TP.HCM', 'Đại học Công nghệ thông tin',
        '028-3722-0808', 'UIT', 'http://www.uit.edu.vn', 1, 1),
       (NULL, NOW(), NULL, NOW(), NULL, NULL, 'contact@tdtu.edu.vn', 'TP.HCM',
        'Đại học Tôn Đức Thắng (Khoa Công nghệ thông tin)', '028-3776-2233', 'TDTU', 'http://www.tdt.edu.vn', 2, 2);

-- 3. Bảng Schedule
INSERT IGNORE INTO `schedule`(created_by_user_id, created_date, last_modified_by_user_id, last_modified_date, name)
VALUES (NULL, NOW(), NULL, NOW(), 'Full time'),
       (NULL, NOW(), NULL, NOW(), 'Part time'),
       (NULL, NOW(), NULL, NOW(), 'Remote');

-- 4. Bảng Position
INSERT
IGNORE INTO `position`(created_by_user_id, created_date, last_modified_by_user_id, last_modified_date, name)
VALUES (NULL, NOW(), NULL, NOW(), 'Front end'),
       (NULL, NOW(), NULL, NOW(), 'Back end'),
       (NULL, NOW(), NULL, NOW(), 'Full Stack'),
       (NULL, NOW(), NULL, NOW(), 'Mobile'),
       (NULL, NOW(), NULL, NOW(), 'Embedded'),
       (NULL, NOW(), NULL, NOW(), 'Tester'),
       (NULL, NOW(), NULL, NOW(), 'DevOps');

-- 5. Bảng Major
INSERT
IGNORE INTO `major`(created_by_user_id, created_date, last_modified_by_user_id, last_modified_date, name)
VALUES (NULL, NOW(), NULL, NOW(), 'Khoa học máy tính'),
       (NULL, NOW(), NULL, NOW(), 'Công nghệ phần mềm'),
       (NULL, NOW(), NULL, NOW(), 'Kỹ thuật máy tính'),
       (NULL, NOW(), NULL, NOW(), 'Trí tuệ nhân tạo'),
       (NULL, NOW(), NULL, NOW(), 'Kỹ thuật mạng'),
       (NULL, NOW(), NULL, NOW(), 'Hệ thống quản lý thông tin');

-- -- 6. Bảng Company
-- INSERT IGNORE INTO `company`(`id`, `created_by_user_id`, `created_date`, `last_modified_by_user_id`, `last_modified_date`,
--                              `description`, `email`, `location`, `logo`, `name`, `personnel_size`, `phone`, `tax`,
--                              `website`, `status_id`)
-- VALUES (1,NULL, NOW(), NULL, NOW(),
--         'hàng đầu Việt Nam về công nghệ thông tin, cung cấp nhân lực toàn Việt Nam', 'abcd1@gmail.com',
--         'Thành phố Hồ Chí Minh', NULL, 'Công ty R2S',
--         '1100', '0087654321', '3014259123', 'abcde1.edu.vn', 1),
--        (2, NULL, NOW(), NULL, NOW(), 'công ty về IT', 'intern@tma.com.vn', '5', NULL,
--         'TMA', '10', '(028) 38912532', '301425912', 'https://www.tma.vn/', 1),
--        (3, NULL, NOW(), NULL, NOW(), 'công ty về IT', 'Recruitment@fsoft.com.vn', '5', NULL,
--         'FPT SOFTWARE', '10', '+84 24 73 044 888', '101601092', 'career.fpt-software.com', 1),
--        (4, NULL, NOW(), NULL, NOW(), 'công ty về IT', 'tuyendung@rakumo.vn', '2', NULL,
--         'Rakumo', '10', '028 3812 0200', '312288873', 'https://rakumo.vn/', 1),
--        (5, NULL, NOW(), NULL, NOW(), 'công ty về IT ', 'tuyendung@fujinet.net', '2', NULL,
--         'FUJINET SYSTEMS JSC', '10', '028 3847 7000', '313424617', 'https://www.fujinet.net/vi', 1),
--        (6, NULL, NOW(), NULL, NOW(), 'công ty về IT ', 'info@axonactive.com', '5', NULL,
--         'AXON', '10', '+84 28 7109 1234', '309699640', 'https://www.axonactive.com/', 1),
--        (7, NULL, NOW(), NULL, NOW(),
--         'Công ty TNHH Đầu tư Phát triển và Chuyển giao công nghệ VINA (VINATTI) được thành lập bởi một nhóm các chuyên gia giàu kinh nghiệm trong lĩnh vực Công nghệ thông tin, Viễn thông và Tài chính. Với định hướng trở thành doanh nghiệp hàng đầu trong lĩnh vực Thương mại – Điện tử tại Việt Nam, VINATTI đã từng bước khẳng định mình qua các dự án cung cấp giải pháp và dịch vụ thanh toán trên nền tảng CNTT tiêu biểu như Hệ thống thanh toán đa dịch vụ tại quầy Bưu điện (Paypost), Hệ thống trung gian thanh toán (Ví điện tử A-PAY),....',
--         'admin@suga.sg', 'Số 1A Trương Quốc Dung, Phường 08, Quận Phú Nhuận, Thành phố Hồ Chí Minh', NULL, 'SUGA',
--         '499', NULL,
--         NULL, ' http://thesugagroup.com/', 1),
--        (8, NULL, NOW(), NULL, NOW(),
--         'TRẢI NGHIỆM CÙNG NHAU VƯƠN TỚI ĐỈNH CAO\nhttps://www.facebook.com/OneMountCareersOne Mount Group được thành lập với tham vọng kiến tạo hệ sinh thái công nghệ lớn nhất Việt Nam, cung cấp các giải pháp và dịch vụ xuyên suốt chuỗi giá trị, từ lĩnh vực dịch vụ tài chính, phân phối, bất động sản và bán lẻ. Bắt đầu với VinShop, ứng dụng bán lẻ chuyên dụng giúp các chủ tiệm tạp hoá độc lập phát triển cửa hàng của họ thông qua công nghệ hỗ trợ quản lý chuỗi cung ứng và hàng tồn kho. VinID, siêu ứng dụng và hệ thống quản lý khách hàng thân thiết lớn nhất Việt Nam tích hợp nhiều chức năng như thanh toán, quản lý nhà ở, mua hàng, dịch vụ tài chính. Và OneHousing, nền tảng toàn diện cho mọi nhu cầu về nhà ở, hỗ trợ mua bán, đầu tư và các dịch vụ khác liên quan đến bất động sản.\nTẦM NHÌN:\nOne Mount Group là đơn vị tiên phong, dẫn dắt và truyền cảm hứng để các doanh nghiệp cùng chung tay nâng cao hiệu quả của nền kinh tế Việt Nam, không ngừng cải thiện cuộc sống của mỗi người dân và giúp đánh thức mọi tiềm năng của xã hội.\nSỨ MỆNH:\nSứ mệnh của One Mount Group là tạo ra hệ sinh thái đáng tin cậy nhất Việt Nam, kết nối con người và doanh nghiệp tại nơi giao thoa giữa công nghệ và nhân văn.\n',
--         'press@onemount.com',
--         '•	Tower 2 Times City, 458 Minh Khai, Phường Vĩnh Tuy, Quận Hai Bà Trưng, Thành phố Hà Nội\n•	Tầng 9 tòa nhà Five Star Tower, 28 Bis Mạc Đĩnh Chi, Phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh\n',
--         NULL, 'One Mount Group', '1000', NULL, NULL, ' https://onemount.com/', 1),
--        (9, NULL, NOW(), NULL, NOW(),
--         'Work Like Tomorrow\nKofax is a leading provider of software to simplify and transform the First Mile™ of business. Success in the First Mile can dramatically improve the customer experience, greatly reduce operating costs and increase competitiveness, growth and profitability. Kofax software and solutions provide a rapid return on investment to more than 20,000 customers in financial services, insurance, government, healthcare, supply chain, business process outsourcing and other markets. Kofax delivers these through its direct sales and service organization, and a global network of more than 800 authorized resellers in more than 70 countries throughout the Americas, EMEA and Asia Pacific. For more information, visit kofax.com.\n\n',
--         'info@kofax.com',
--         '11 Fl., A tower, Handi Resco Bld., 521 Kim Mã str., Phường Ngọc Khánh, Quận Ba Đình, Thành phố Hà Nội', NULL,
--         'KOFAX', '100', NULL, NULL, 'https://www.kofax.com/', 1),
--        (10, NULL, NOW(), NULL, NOW(),
--         'DataStreams sẽ là đối tác tốt nhất để phát huy sức mạnh của dữ liệu của bạn\nNhiều công ty rơi vào tình trạng khó khăn vì không thể sử dụng dữ liệu mà họ đang có một cách hiệu quả cho dù khi họ sở hữu nhiều dữ liệu. Trong những trường hợp này, các công ty đó cần tìm một công ty chuyên môn về công nghệ thông tin mà có thể hỗ trợ giải pháp và dịch vụ tư vấn phù hợp. DataStreams đang xây dựng các giải pháp đẳng cấp thế giới có thể xử lý, quản lý và truyền đạt dữ liệu của người sử dụng một cách an toàn và hiệu quả trên bất kỳ nền tảng dữ liệu nào.\nTại sao phải là DataStreams - Expert for BigData, ETL, Data Governance, Data Management Solution\nDựa trên kinh nghiệm và bí quyết đa dạng được tích lũy trong lĩnh vực quản lý dữ liệu, DataStreams hiểu rõ nhu cầu của khách hàng, chẩn đoán trước dữ liệu của khách hàng và đề xuất các giải pháp phù hợp theo kết quả chẩn đoán.\nVì công ty chúng tôi có công nghệ sản phẩm hoàn chỉnh nên những khách hàng đang sử dụng sản phẩm của chúng tôi có thể nâng cao năng lực quản lý dữ liệu dần dần từng bước mà không chịu ảnh hưởng đặc biệt nào đến hệ điều hành. Đặc biệt, DataStreams đang cung cấp các giải pháp với mức giá hợp lý so với các giải pháp nước ngoài khác, đồng thời cung cấp các chức năng đa dạng, tính năng vượt trội và dịch vụ hỗ trợ kỹ thuật ổn định.\n',
--         'marketing@datastreams.co.kr',
--         'Tầng 25, Keangnam Landmark 72, Phạm Hùng, Phường Mễ Trì, Quận Nam Từ Liêm, Thành phố Hà Nội', NULL,
--         'DataStreams Asia', '499', NULL, NULL, 'http://datastreams.co.kr/vt/', 1),
--        (11, NULL, NOW(), NULL, NOW(),
--         'Mang lại giá trị đích thực\nTập Đoàn Công nghệ Quảng Ích\nTập Đoàn Công Nghệ Quảng Ích - QIG được thành lập trên cơ sở công ty cổ phần phần mềm Quảng Ích và các công ty con. Tập đoàn được hình thành với mục tiêu trở thành Tập đoàn công nghệ số 1 Việt Nam về các giải pháp công nghệ ứng dụng ở lĩnh vực giáo dục và các lĩnh vực có tính xã hội cao. Sau gần 20 năm hình thành và phát triển, công ty đã gặt hái được nhiều thành tựu và mang lại nhiều giá trị thiết thực cho các khách hàng, các sản phẩm và dịch vụ của công ty đã triển khai tới hàng triệu khách hàng trên toàn quốc.\nTầm Nhìn\n   Trở thành Tập đoàn công nghệ số 1 trong cung cấp các sản phẩm dịch vụ phần mềm cho giáo dục phổ thông tại Việt nam.\n   Xây dựng tổ chức với các giá trị tốt đẹp, văn minh và lan tỏa xã hội.\nSứ mệnh\n   Xây dựng hệ sinh thái phần mềm để chuyển đổi số toàn diện trong giáo dục phổ thông: Quản lý, Thư viện, Học tập và đánh giá, Kết nối nhà trường và gia đình.\n   Giúp ngành giáo dục (nhà quản lý, giáo viên, phụ huynh, học sinh) dễ dàng tiếp cận và ứng dụng công nghệ để nâng cao chất lượng quản lý, giảng dạy và học tập.\n',
--         'info@quangich.comquangich.',
--         '•	Z5-46 TTTM LePARC, KM 1,5 Pháp Vân, CV Yên Sở, Phường Yên Sở, Quận Hoàng Mai, Thành phố Hà Nội\n•	Tầng 09, Tòa nhà CIC TOWER tại ngõ 219 phố Trung Kính, Phường Yên Hoà, Quận Cầu Giấy, Thành phố Hà Nội\n\n',
--         NULL, 'Công ty Cổ Phần Công nghệ Quảng Ích', '499', NULL, NULL, 'https://qig.vn/', 1),
--        (12, NULL, NOW(), NULL, NOW(),
--         'TMA Technology Group – Tập đoàn Công nghệ hàng đầu Việt Nam\nĐược thành lập năm 1997, TMA là tập đoàn công nghệ hàng đầu Việt Nam với hơn 3,800 kỹ sư. TMA có 6 văn phòng tại TP.HCM, Công viên Sáng tạo TMA tại Bình Định và 6 văn phòng tại nước ngoài (Canada, Mỹ, Đức, Úc, Nhật Bản và Singapore).\nVới sự phát triển vững mạnh 25 năm qua, TMA tự hào nhận được sự tin tưởng của khách hàng là những tập đoàn lớn đến từ 30 quốc gia trên thế giới. TMA nhiều năm liền vinh dự được bình chọn trong top doanh nghiệp CNTT Việt Nam, liên tục được vinh danh trong top 10 doanh nghiệp xuất khẩu phần mềm, Top 10 doanh nghiệp Fintech, Top 10 doanh nghiệp AI – IoT…\nĐặt yếu tố con người lên hàng đầu, TMA với môi trường làm việc chuyên nghiệp và thân thiện, luôn nỗ lực tạo ra đời sống văn hóa phong phú, sôi động, để nhân viên TMA luôn cảm thấy thoải mái, xem công ty không chỉ là nơi làm việc, mà còn là nơi có các hoạt động vui chơi, giải trí đầy thú vị, hấp dẫn. \nCùng với đó, TMA còn có rất nhiều phúc lợi hấp dẫn như:\n⮚ Lương thưởng cạnh tranh\n⮚ Nhiều cơ hội thăng tiến \n⮚ Bảo hiểm chăm sóc sức khỏe nhân viên toàn diện với mức bảo hiểm cao\n⮚ Hệ thống đào tạo nội bộ với hàng trăm khóa học mỗi năm \n⮚ Hàng trăm cơ hội công tác nước ngoài mỗi năm\nHãy gia nhập TMA ngay hôm nay!\n\n',
--         'recruit@tma.com.vn',
--         '•	Tòa nhà TMA, Công viên phần mềm Quang Trung, Phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh\n•	111 Nguyễn Đình Chính, Phường 15, Quận Phú Nhuận, Thành phố Hồ Chí Minh\n',
--         NULL, 'TMA Tech Group', '1000', NULL, NULL, 'https://www.tma.vn/', 1),
--        (13, NULL, NOW(), NULL, NOW(),
--         'GIÁO DỤC ĐỂ PHÁT TRIỂN - ĐÀO TẠO ĐỂ LÀM VIỆC - TRẢI NGHIỆM ĐỂ TRƯỞNG THÀNH\nNỘI DUNG HOẠT ĐỘNG\n•	ĐÀO TẠO & GIÁO DỤC, phát triển kỹ năng hướng nghiệp \n•	PHÁI CỬ THỰC TẬP SINH, thực tập tại Nhật Bản \n•	ĐÀO TẠO & GIỚI THIỆU KỸ SƯ, làm việc tại Nhật Bản \n•	GIỚI THIỆU VIỆC LÀM TRONG NƯỚC, thay đổi ý thức – thăng tiến nghề nghiệp \n•	TƯ VẤN ĐẦU TƯ CHO CÁC DOANH NGHIỆP NHẬT BẢN, tận dụng cơ hội đầu tư tại Việt Nam \n•	TƯ VẤN THIẾT KẾ KỸ THUẬT CÔNG NGHỆ CAO, đào tạo phát triển kỹ sư trẻ Việt Nam  \n•	TƯ VẤN CHĂM SÓC SỨC KHỎE NGƯỜI CAO TUỔI TRONG NƯỚC, chất lượng tiêu chuẩn Nhật Bản \n',
--         'contact@esuhai.com', '40/12 - 40/14 Ấp Bắc, Phường 13, Quận Tân Bình, Thành phố Hồ Chí Minh', NULL,
--         'CÔNG TY TNHH ESUHAI', '499', NULL, NULL, 'https://esuhai.vn/', 1),
--        (14, NULL, NOW(), NULL, NOW(),
--         'ESATECH - Services, Solutions, Electronics, Automations\nCông ty Cổ phần Công nghệ ESA Việt Nam - ESATECH là nhà cung cấp giải pháp một cửa cho sản xuất và vận chuyển thông minh.\nChúng tôi nghiên cứu, phát triển và tích hợp các giải pháp điều khiển cốt lõi cho xe có dẫn hướng tự động AGV, robot di động tự động - AMR, Xe nâng tự động - Automated Forklift.\nTầm nhìn:\n•	Đẩy mạnh mạng lưới nghiên cứu phát triển, ứng dụng công nghệ mới để tạo ra các sản phẩm ổn định, mạnh mẽ và thông minh hơn;\n•	Tăng cường hợp tác với các đối tác trong và ngoài nước để ứng dụng sản phẩm vào môi trường sản xuất thực tế, mở rộng lãnh thổ kinh doanh\n',
--         'info@esatech.vn',
--         '•	Số 265 đường Chiến Thắng, Phường Văn Quán, Quận Hà Đông, Thành phố Hà Nội\n•	Số 282 Đường Phan Trọng Tuệ, Xã Thanh Liệt, Huyện Thanh Trì, Thành phố Hà Nội\n',
--         NULL, 'Esa Việt Nam', '99', NULL, NULL, 'https://esa.vn/', 1),
--        (15, NULL, NOW(), NULL, NOW(),
--         'LPBank - Liên Kết Phát Triển\nNgân hàng Thương mại Cổ phần Bưu điện Liên Việt (LPBank) tiền thân là Ngân hàng Thương mại Cổ phần Liên Việt (LienVietBank) được thành lập theo Giấy phép thành lập và hoạt động số 91/GP-NHNN ngày 28/03/2008 của Thống đốc Ngân hàng Nhà nước Việt Nam.\nNăm 2011, với việc Tổng Công ty Bưu chính Việt Nam góp vốn vào LienVietBank bằng giá trị Công ty Dịch vụ Tiết kiệm Bưu điện (VPSC) và bằng tiền mặt. Ngân hàng Liên Việt đã được Thủ tướng Chính phủ và Thống đốc Ngân hàng Nhà nước Việt Nam cho phép đổi tên thành Ngân hàng Thương mại Cổ phần Bưu điện Liên Việt. Cùng với việc đổi tên này, Tổng Công ty Bưu chính Việt Nam chính thức trở thành cổ đông lớn nhất của LPBank\nSau 15 năm thành lập và hoạt động, LPBank đã phát triển thành 1 trong top 10 NHTMCP lớn nhất Việt Nam với tổng tài sản trên 327.000 tỷ đồng, vốn điều lệ đạt 17.241 tỷ đồng. Hiện LPBank cũng là một trong những NH có mạng lưới rộng nhất trong hệ thống NH với 561 chi nhánh, phòng giao dịch và hơn 10.000 điểm cung cấp dịch vụ. Tổng số nhân sự của LPBank đã lên tới hơn 12.000 người.\n',
--         'tuyendung@lienvietpostbank.com.vn',
--         '•	Tòa nhà LPBank, số 210 Trần Quang Khải, Phường Tràng Tiền, Quận Hoàn Kiếm, Thành phố Hà Nội\n•	2A Nguyễn Thị Minh Khai, Phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh\n•	140 Nguyễn Thị Minh Khai, Phường Hải Châu I, Quận Hải Châu, Thành phố Đà Nẵng\n',
--         NULL, 'NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN BƯU ĐIỆN LIÊN VIỆT', '19999', NULL, NULL,
--         'https://jobs.lienvietpostbank.com.vn/vi',
--         1),
--        (16, NULL, NOW(), NULL, NOW(),
--         'LET’S MAKE IT HAPPEN. Let’s create the future\nWE ARE FRACTAL - Leading Software Development Company in Vietnam. Established in July 2017, Fractal is a Software Solutions company , developing tailor made Sale/ Marketing solutions that help  Enterprises digitalizing operations and data procession.  We always try our best to stand out from the crowd of other software developments. Client satisfaction is our highest goal. Get inspired by client business, strike the best to help them pursuing success is our core mindset.  Be honored to serve most famous company in several industries: FMCG, Pharmacy, Transportation, Retails & Ecommerce.\n',
--         'thai.ngo@fractal.vn',
--         'Tầng 2, Tòa nhà Thái Sơn, 153 Ung Văn Khiêm, Phường 25, Quận Bình Thạnh, Thành phố Hồ Chí Minh', NULL,
--         'CÔNG TY CỔ PHẦN CÔNG NGHỆ FRACTAL', '99', NULL, NULL, 'http://fractal.vn/', 1),
--        (17, NULL, NOW(), NULL, NOW(), 'description', 'dragonball@gmail.com', NULL, NULL, 'Dragon Ball', '100-200',
--         '0912333333',
--         '123456', 'www.dragonball.com', 1),
--        (18, NULL, NOW(), NULL, NOW(), 'description', 'dragonball@gmail1.com', NULL, NULL, 'Dragon Ball 1', '100-200',
--         '0912333333',
--         '1234567', 'www.dragonball1.com', 1);
--
-- -- 7. Bảng Job
-- INSERT IGNORE INTO `job`(`id`, `created_by_user_id`, `created_date`, `last_modified_by_user_id`, `last_modified_date`,
--                          `amount`, `description`, `end`, `location`, `name`, `other_info`, `requirement`, `salary_max`,
--                          `salary_min`, `start`, `company_id`, `status_id`)
-- VALUES (1, NULL,NOW(),NULL,NOW(),5,'làm về JAVA','2023-05-24 00:00:00','Binh Loi ','Thực tập','Lương: 30.000.000 - 50.000.000 đồng/tháng. \r\nLàm việc cùng team tech trẻ trung, đầy nhiệt huyết và năng động. \r\nCơ hội học hỏi và làm việc trực tiếp cùng các Leader đầy kinh nghiệm.','Có tối thiểu 2 tháng làm việc với JAVA',500,10,'2023-03-10 00:00:00',3,1),
--        (2, NULL,NOW(),NULL,NOW(),4,'Tham gia vào các dự án thiết kế, phát triển các sản phẩm mới theo yêu cầu của khách hàng hoặc từ Leader.\nTham gia bảo trì, nâng cấp chức năng, giao diện theo yêu cầu của khách hàng trên hệ thống website hiện có.\nTham gia phân tích yêu cầu, thiết kế, cài đặt và review code sử dụng một trong các framework của Javascript.\nNghiên cứu và ứng dụng các công nghệ mới vào phát triển sản phẩm.\nBáo cáo kết quả công việc cho PM.','2023-07-14 04:43:16','77 Thống Nhất, Quận Bình Thạnh, Thành phố Hồ Chí Minh','Thực tập BA','Trợ cấp thực tập: 3.000.000 - 5.000.000 đồng/tháng.\\r\\nLàm việc cùng team tech trẻ trung, đầy nhiệt huyết và năng động.\\r\\nCơ hội học hỏi và làm việc trực tiếp cùng các Leader đầy kinh nghiệm.','Yêu cầu ứng viên\\r\\nNắm vững kiến thức về HTML/CSS, JS/JQuery/AJAX/Bootstrap/Responsive.\\r\\nNắm vững ngôn ngữ lập trình JavaScript.\\r\\nHiểu biết về REST API.\\r\\nCó khả năng làm việc tốt với ReactJs, Next.Js\\r\\nCó khả năng tự học, và linh hoạt khi làm việc với các framework khác của Javascript. (NodeJs, ReactJs, Ghost, Strapi) để phát triển dự án.\\r\\n• Có tư duy logic tốt.\\r\\n• Có kỹ năng lên kế hoạch công việc và quản lý thời gian tốt.\\r\\n• Có kỹ năng làm việc nhóm tốt.\\r\\n• Chịu được áp lực và hoàn thành công việc đúng deadline.',1000000,5000000,'2023-05-10 04:43:16',4,1),
--        (3, NULL,NOW(),NULL,NOW(),8,'•	Tham gia phát triển các dự án game của công ty\n•	Làm việc trực tiếp với Product Owner/Designer để làm UI cho mini/puzzle game và casino game, landing page và website\n•	Nhận task từ leader, tham gia phân tích thiết kế hệ thống hoặc framework, research  dựa trên require dự án \n•	Thời gian làm việc: Từ thứ 2 đến thứ 6 (8h/ngày). Riêng thứ 7 thì 2 lần trong tháng(chủ yếu đến công ty để giao lưu học hỏi giữa các team trong công ty)\n','2023-05-19 04:43:16','Số 1A Trương Quốc Dung, Phường 08, Quận Phú Nhuận, Thành phố Hồ Chí Minh','GAME BACKEND DEVELOPER','•	Mức lương thỏa thuận dựa trên năng lực ứng viên\n•	Trợ cấp ăn trưa(700.000- ăn tại công ty và không quy đổi sang tiền mặt)\n•	Trợ cấp chi phí gửi xe.\n•	Trợ cấp chi phí kết nối team mỗi 4 tháng/lần.\n•	Giảm ưu đãi các sản phẩm từ công ty như: Coffee HiPB, Hidental (nha khoa)...\n•	Được đề xuất, xét thưởng và xét tăng lương định kỳ 6 tháng 1 lần\n•	Full lương tháng 13, thưởng tết\n•	Được thưởng lợi nhuận dự án (10% profit của product sẽ share cho team)\n•	Full các chế độ như: BHXH, BHYT, Teambuilding,Khám sức khỏe\n•	Các chế độ khác như: nghỉ phép, lễ… theo chế độ mà bộ luật lao động Việt Nam quy định\n•	Được tiếp cận những thách thức để chinh phục, nhiều cơ hội thăng tiến và phát triển.\n•	Được làm việc trong môi trường năng động, trẻ trung\n•	Được đào tạo những kỹ năng mới phục vụ cho công việc\n•	Mức thu nhập tương xứng với năng lực và trình độ\n•	Được hướng dẫn, đào tạo kỹ năng cũng như xét tuyển thăng tiến các vị trí trong công việc.\n','•	Làm việc full-time \n•	Có khả năng giao tiếp tốt, làm việc trong môi trường teamwork hiệu quả.\n•	Có tinh thần học hỏi, cầu tiến. Có tinh thần trách nhiệm cao, sẵn sàng tiếp nhận thử thách trong công việc và đảm bảo hoàn thành được công việc đúng kế hoạch\n•	Kỹ năng quản lý thời gian tốt\n•	Tiếng anh tốt là một lợi thế \n•	Nắm vững cơ bản lập trình hướng đối tượng, kiến thức liên quan đến RESTful API, socket networking, web service\n•	Có kinh nghiệm làm việc với NodeJS, Spring Boot\n•	Có kiến thức về SQL, ElasticSearch, MongoDB\n•	Yêu thích đam mê làm game là một lợi thế\n\n\n',25000000,10000000,'2023-05-19 04:43:16',5,1),
--        (4, NULL,NOW(),NULL,NOW(),4,'•	Writing clean & high-quality code\n•	Maintain & improve running- functionality as well as design and develop new system, new feature if needed\n•	Deliver end-to-end, including unit test, integration test and deployment to PROD\n•	Participate in code reviews & control coding quality standards\n','2023-05-16 04:43:16','Tầng 9 tòa nhà Five Star Tower, 28 Bis Mạc Đĩnh Chi, Phường Đa Kao, Quận 1, Thành phố Hồ Chí Minh','Back-End Engineer (Java)','•	Competitive income with lunch allowance, 13 fixed months salary, performance bonus and gift on special occasion.\n•	Annual leave: 15 - 20 days/year, birthday leave and other leaves/public holidays in accordance with the Labor Law of Vietnam\n•	Periodic medical checkup, Health/Social Insurances & PVI Insurance\n•	Be provided with high performance laptop and screen\n•	Modern and flexible Agile Office fully equipped with gaming, yoga, gym, lunch area, personal locker, open space... No dress code, just shine your way.\n','•	5+ years of handson development experience in Java and its frameworks (Spring Framework, Spring boot)\n•	Good knowledge of Data Structures and Algorithms\n•	Expertise in SQL / NoSQL Databases (MySQL, PostgreSQL, MongoDB)\n•	Experience with RESTful APIs, Microservices\n•	Familiarity with Redis, Kafka\n•	Experience with Docker/Kubernetes and Cloud Infrastructure is a plus\n•	Experience with Agile or Scrum software development methodologies\n',0,0,'2023-05-22 04:43:16',2,1),
--        (5, NULL,NOW(),NULL,NOW(),2,'Analysts in the CDO team work with the business and product owner to create the backlog of epics and user stories for the team to build. They explore the data and processes to support this effort, create dashboards to help measure and communicate key metrics and test solutions built to ensure alignment with functional acceptance criteria.\n\n•	Lead the effort to communicate state of the business to stakeholders regularly - enable audiences to understand the reasons behind the trends - and provide insights to drive strategic decisions.\n•	Conduct exploratory analysis - go deep into the data to develop hypotheses and to answer complex business questions\n•	Develop tools and automated processes that project the work out to a broader audience. Strategize on democratizing data and insights to make analyses easily repeatable and generalizable by other team members in the future\n•	Ownership of conceptualizing, developing, and maintaining dashboards, visualizations\n•	Develop analytics frameworks and foundations to enable easy actionable insights and reliable measurement\n•	Become a data expert in your business domain and own data quality\n•	Empower the team to answer data questions quickly and easily by building high-quality ground truth data sets\n\n','2023-06-20 04:43:16','Tower 2 Times City, 458 Minh Khai, Phường Vĩnh Tuy, Quận Hai Bà Trưng, Thành phố Hà Nội','Data Analyst','13 months salary fixed','Key Skills\n•	Ability to translate business process and customer outcomes to user stories, requirements & specifications. \n•	Ability to work with business & technical stakeholders.\n•	Advanced SQL and data analysis skills. AGILE trained.\n•	2+ years experience in similar role.\nDomain Expertise\n•	Retail, Ecommerce, Supply Chain, Real Estate Services is plus\n•	Data modelling and data warehousing in general\nIndividual Skills\n•	Good communication skills - verbal and written\n•	Proactive problem solver, eye for detail, process driven\n•	AGILE trained, can elicit user stories, draw process diagrams\n•	Data modelling experience\n•	Good understanding of data management - data lineage, meta data, data quality, data governance\nAnalytics Experience\n•	Strong SQL and data analysis skill\n•	Visualisation with tools such as Power BI, Tableau etc.\n•	Data modelling & datamart experience\n•	Experience with an ETL framework like Airflow\n•	Nice to have - Python and R programming\n\n',0,0,'2023-05-22 04:43:16',8,1),
--        (6, NULL,NOW(),NULL,NOW(),8,'•	Plan, develop, and execute test automation scripts for functional testing with scripting languages/frameworks such as Selenium, Robot, etc.\n•	Create and maintain test documentation such as defect reports and test result summaries.\n•	Interact with team members and other groups to ensure all requirements have been tested, defects have been documented, and quality issues identified during the testing process have been resolved.\n•	Communicate product and process information to other members of the team, other departments, and customers as necessary.\n','2023-06-20 04:43:16','11 Fl., A tower, Handi Resco Bld., 521 Kim Mã str., Phường Ngọc Khánh, Quận Ba Đình, Thành phố Hà Nội','Test Automation Engineer','•	Attractive salary (gross monthly salary of 18,000,000 - 25,000,000 VND)\n•	Stable and long-term job (Many employees of ours have been with us for longer than 10 years. We develop our own world-class products, not doing outsourcing).\n•	Annual salary review and adjustment.\n•	Professional working environment (Come and enjoy our powerful machines, licensed software, workspace with partitions, flexible working hours and no working overtime).\n•	Advanced health insurance for the whole family (Let the international hospitals take care of not only your health but also your loved ones\')\n•	Full salary contribution to social, health, and unemployment insurances (we will contribute an additional amount of 21.5% of your gross salary for your insurance benefits, including a good pension in future. Many other companies just offer an insurance package of minimum basic salary and so, the employees will have almost no income after retiring)\n•	Mon -Fri\n','•	Proficient in developing test automation scripts for functional testing with Selenium framework\n•	Knowledge of other software testing tools such as TestNG, RestAssured, Jmeter, Granafa, InfluxDB, SureFire, PyTest, Jacoco, SonarCloud, etc.\n•	Experience in installation, configuration, and troubleshooting of enterprise server and client applications in a virtual environment.\n•	Familiar with Agile and waterfall environments for fast-paced software development and testing release cycle.\n•	Good command of English.\n',25000000,18000000,'2023-05-13 04:43:16',9,1),
--        (7, NULL,NOW(),NULL,NOW(),2,'•	Nghiên cứu, phân tích các tài liệu yêu cầu, thiết kế.\n•	Thiết kế và viết testcase, test script, checklist.\n•	Tham gia lập các bộ tài liệu test: Quy trình test, Testplan.\n•	Thực hiện kiểm thử, phát hiện lỗi, log lỗi và quản lý lỗi trên hệ thống Quản lý lỗi, phối hợp với developer để sửa lỗi.\n•	Test nghiệm thu sản phẩm, Xây dựng tài liệu hướng dẫn sử dụng, hướng dẫn cài đặt cho sản phẩm.\n•	Hướng dẫn, hỗ trợ khách hàng, hỗ trợ triển khai sản phẩm.\n•	Xây dựng báo cáo kết quả test. Báo cáo công việc với test lead.\n•	Đối với các ứng viên trên 3 năm kinh nghiệm được xem xét apply vào các vị trí test lead\n','2023-06-15 04:43:16','Tầng 25, Keangnam Landmark 72, Phạm Hùng, Phường Mễ Trì, Quận Nam Từ Liêm, Thành phố Hà Nội','[HN] Tester - Nhân Viên Kiểm Thử Phần Mềm','•	Performance Bonus\n•	Loyalty Bonus\n•	13th-month salary\n•	Technical Training in Korea\n•	Team building program\n•	Onsite Business trip\n•	Maternity Leave\n•	Annual Leave\n•	Insurance\n•	Happy meal\n•	Working hours: Monday to Friday from 08:30 to 17:30\n','•	Tốt nghiệp ĐH chuyên ngành IT hoặc các chuyên ngành liên quan. Hoặc ứng viên trái ngành đã có kinh nghiệm làm việc trong lĩnh vực kiểm thử.\n•	Nắm vững quy trình kiểm thử phần mềm.\n•	Có kỹ năng phân tích kết quả kiểm thử và báo cáo.\n•	Ưu tiên có các chứng chỉ về kiểm thử phần mềm: ISTQB\n•	Có kinh nghiệm xây dựng test case và thực hiện test.\n•	Có thể làm việc với cơ sở dữ liệu như MySQL, Oracle, SQL Server là một lợi thế....\n•	Đọc hiểu được tài liệu Tiếng Anh\n•	Vị trí test lead: nắm rõ qui trình test, qui trình phát triển sản phẩm, có kinh nghiệm quản lý dự án, xây dựng kế hoạch/báo cáo.\n•	Chấp nhận ứng viên chưa có kinh nghiệm (frehser) \n',10000000,5000000,'2023-05-23 04:43:16',10,1),
--        (8, NULL,NOW(),NULL,NOW(),2,'•	Lập test plan, viết test case, chuẩn bị dữ liệu và môi trường test.\n•	Thực hiện kiểm thử, phát hiện lỗi và phối hợp với các developer để sửa lỗi.\n•	Log bugs, đánh giá mức độ quan trọng và mức độ khẩn cấp của bug.\n•	Phân tích và theo dõi kết quả test, báo cáo kết quả test.\n•	Tham gia nghiên cứu và đề xuất các cải tiến các chức năng, quy trình kiểm thử sản phẩm.\n•	Phân tích nghiệp vụ và lập test case.\n•	Đào tạo, chuyển giao nghiệp vụ cho team CSKH và Vận hành ứng dụng.\n','2023-06-10 04:43:16','•	Tầng 09, Tòa nhà CIC TOWER tại ngõ 219 phố Trung Kính, Phường Yên Hoà, Quận Cầu Giấy, Thành phố Hà Nội','[HN] Tester - Nhân Viên Kiểm Thử Phần Mềm','•	Mức lương theo kinh nghiệm ứng viên: từ 13-20tr triệu/tháng.\n•	Phụ cấp ngoài lương: Ăn trưa, gửi xe...\n•	Được đóng bảo hiểm xã hội, bảo hiểm thất nghiệp, bảo hiểm y tế và các quyền lợi khác theo quy định của pháp luật.\n•	Thưởng tháng: căn cứ vào chính sách của phòng ban.\n•	Thưởng cuối năm: phụ thuộc vào hiệu quả công việc cá nhân, bộ phận và tình hình kinh doanh của công ty.\n•	Thưởng đột xuất (thưởng nóng) nếu có hoàn thành tốt KPI.\n•	Môi trường làm việc: Trẻ trung, năng động, được tạo điều kiện để phát huy tối đa năng lực, nhiều cơ hội thăng tiến.\n•	Xét nâng lương định kỳ 1 lần/ năm và đột xuất nếu hoàn thành xuất sắc công việc.\n•	Được xem xét tham gia chương trình ESOP để gắn bó lâu dài với công ty.\n•	Được hưởng các quyền lợi và chế độ theo luật định (nghỉ lễ, BHXH, BHYT…), chế độ phúc lợi hàng năm của công ty.\n•	Chế độ lương làm thêm giờ (OT) theo đúng quy định của pháp luật.\n•	Nghỉ mát tại khách sạn 5 sao\n•	Lựa chọn làm việc tại 1 trong 2 địa điểm: Trung Kính (Yên Hòa - Cầu Giấy) hoặc Gamuda City (Yên Sở - Hoàng Mai)\n','•	Có từ 1 năm trở lên kinh nghiệm Tester.\n•	Nhanh nhẹn, chăm chỉ, khả năng học hỏi cao, và có trách nhiệm trong công việc.\n•	Nắm vững và hiểu biết sâu về quy trình Test, các kỹ thuật Testing.\n•	Có kinh nghiệm Test trên một trong các nền tảng các ứng dụng Web, Web Application, Mobile Application là một lợi thế.\n•	Có kỹ năng làm teamwork hoạt động đội nhóm tốt.\n•	Ưu tiên những ứng viên có kinh nghiệm làm việc với phần mềm có tính nghiệp vụ cao.\n•	Ưu tiên ứng viên có kỹ năng đào tạo.\n\n',20000000,13000000,'2023-05-19 04:43:16',11,1),
--        (9, NULL,NOW(),NULL,NOW(),5,'•	Develop and enhance software through coding and testing.\n•	Deliver highest software quality by creating unit test.\n•	Adapt with the application and processes used in software development.\n•	Implements solutions as designed in technical documentation specification and coding standards.\n•	Reports to a technical lead.\n•	Bug fix and troubleshoot.\n','2023-06-19 04:43:16','Tòa nhà TMA, Công viên phần mềm Quang Trung, Phường Tân Chánh Hiệp, Quận 12, Thành phố Hồ Chí Minh','Full stack Developer (.NET/ReactJS)','•	13th salary and bonus based on business performance;\n•	Performance review each year and salary adjustment based on job performance\n•	Healthcare: Annual health check-up, Premium Health Insurance\n•	Comfortable working conditions and flexible working time\n•	Good career growth opportunities with interesting and challenging projects;\n•	English, technical, and soft skills training courses;\n•	Outdoor activities with company support: sports clubs, team building, happy hour parties, birthdays, trips, staff and family events, etc.\n•	Time work: Mon -Fri (8:30 - 12:00 - 1:30 - 6:00)\n','•	Good at programming language (C#) and framework (.NET or .NET Core)\r •	Good at Entity Framework\r •	Good at Object Oriented Programming (OOP), SOLID principles\r •	Has knowledge on design patterns (singleton, factory, bridge, building) programming specifically on C#\r •	Worked with RESTful APIs\r •	Has knowledge on SQL\r •	Knowledge on one of FE frameworks as Angular, React, Vue is a plus\r •	Knowledge on one of UI frameworks as Bootstrap, Material, Ant Design is a plus\r •	Fast learner, self-motivated, good problem-solving skills\r •	Highly accurate and detail-oriented.\r •	Good communication in English\r •	Familiar with tools: SVN/Git, Visual Studio, Visual Studio Code, SQL Server Management\r ',0,0,'2023-05-19 04:43:16',12,1),
--        (10, NULL,NOW(),NULL,NOW(),2,'•	Lập trình phát triển các ứng dụng quản lý trong công ty trên nền tảng .NET .\n•	Lập trình FE dựa trên framework Angular, Ant design\n•	Phân tích yêu cầu, thiết kết giao diện theo yêu cầu để đáp ứng nhu cầu của người dùng.\n•	Tối ưu hoá code để tăng tốc độ, trải nghiệm cho người dùng.\n•	Bảo trì, nâng cấp các ứng dụng quản lý nội bộ\n•	Hỗ trợ các công việc dự án phát sinh theo chỉ đạo từ trưởng phòng ban\n','2023-05-31 04:43:16','40/12 - 40/14 Ấp Bắc, Phường 13, Quận Tân Bình, Thành phố Hồ Chí Minh','Nhân viên lập trình Front-end (HTML/CSS/JavaScript)','•	Lương theo năng lực thực tế; điều chỉnh định kỳ hằng năm, năm đầu chế độ điều chỉnh 2 lần\n•	 Thưởng hiệu quả công việc: 2 kỳ / năm & các kỳ thưởng lễ (30/04, 02/09, 20/11, 01/01)\n•	 Phụ cấp ngoài giờ, Phụ cấp di chuyển chi nhánh, Phụ cấp công tác.\n•	 Thăm bệnh, Khám sức khỏe định kỳ hằng năm, Tham gia BHXH-BHYT, Chế độ Bảo hiểm cao cấp đối với nhân viên thâm niên,…\n•	 Trợ cấp nhà xa, Cơm trưa, Môi trường làm việc, Thai sản,..\n•	 Phúc lợi Sinh nhật, Đám cưới, Sinh con\n•	 Tham gia các sự kiện: du lịch, teambuilding, …\n•	 Làm việc: Từ thứ Hai đến sáng Thứ 7 (nghỉ chiều thứ 7 và chủ nhật)\n•	Outdoor activities with company support: sports clubs, team building, happy hour parties, birthdays, trips, staff and family events, etc.\n•	Time work: Mon -Fri (8:30 - 12:00 - 1:30 - 6:00)\n','•	Có từ 2 năm kinh nghiệm trở lên\n•	Có kinh nghiệm và kiến thức vững về các công cụ lập trình giao diện: HTML/ CSS, Responsive, JavaScript, Bootstrap, Ant Design, Tailwind CSS, Material UI, ...\n•	Có kiến thức về lập trình Database, SQL server\n•	Có kiến thức về các framework JavaScript như Angular, React là điểm cộng\n•	Có kiến thức và kinh nghiệm lập trình Mobile là một lợi thế (React Native, Xamarin, Flutter,...)\n•	Có kiến thức về quy trình phát triển phần mềm theo mô hình Agile là lợi thế\n•	Khả năng giao tiếp và xử lý vấn đề tốt\n•	Có khả năng đọc hiểu tài liệu tiếng Anh\n•	Có thể làm việc trong môi trường áp lực cao\n',25000000,15000000,'2023-05-10 04:43:16',13,1),
--        (11, NULL,NOW(),NULL,NOW(),10,'•	Chịu trách nhiệm thiết kế, duy trì và phát triển các hệ thống web theo yêu cầu.\n•	Cùng trao đổi team để phân tích, xây dựng, thiết kế hệ thống.\n•	Trao đổi với designer, BA về thiết kế UI/UX của sản phẩm.\n•	Đảm bảo đáp ứng các tiêu chuẩn về đồ họa trên giao diện.\n•	Thống nhất với Backend team về API và thực hiện tích hợp API.\n•	Tham gia vào review code front end.\n•	Ngoài ra chi tiết công việc sẽ được trao đổi khi phỏng vấn. \n','2023-05-31 04:43:16','Số 265 đường Chiến Thắng, Phường Văn Quán, Quận Hà Đông, Thành phố Hà Nội','Front-end Developer ( Angular/JS/HTML5/CSS3)','•	Mức lương: 14 – 35 triệu theo năng lực thực tế , tăng lương theo thâm niên công tác.\n•	Cấp máy tính, thiết bị làm việc.\n•	Cơ hội được đào tạo liên tục nâng cao chuyên môn và các kỹ năng làm viêc.\n•	Lộ trình thăng tiến, tăng lương rõ ràng.\n•	Đóng BHXH đẩy đủ và đúng luật.\n•	Có nhiều đợt thưởng trong năm: Thưởng lễ 30-4, thưởng ngày truyền thống, thưởng 6 tháng đầu năm, thưởng ngày thành lập công ty, thưởng Tết Dương, thưởng Tết âm (thưởng năm) và các giải thưởng cá nhân khác: Tiên tiến, xuất sắc, tiềm năng, có cố gắng….\n•	Hỗ trợ tiền điện thoại. Hỗ trợ tiền ăn trưa.\n•	Có chế độ chăm sóc y tế cho nhân viên, du lịch 1 năm/1 lần (trong nước hoặc nước ngoài) và tham gia các hoạt động vui chơi giải trí khác (sinh nhật công ty, sinh nhật các thành viên…)\n•	Có cơ hội được làm việc và công tác ở nước ngoài (Thái Lan, Malaysia, Singapore, Ấn Độ, Đức)\n•	Nghỉ 2 ngày thứ 7 trong tháng và các chủ nhật, chế độ phép đầy đủ theo quy định.\n','•	Yêu cầu có từ 1-3 năm kinh nghiệm lập trình FE thực tế.\n•	Có ít nhất 1-3 năm kinh nghiệm làm việc trong các dự thực tế.\n•	Hơn 4 năm kinh nghiệm xây dựng các sản phẩm dựa trên web với các Front-End hiện đại và tiên tiến, chẳng hạn như Bootstrap, Angular.\n•	Thành thạo HTML5, CSS3, JavaScript, TypeScript.\n•	Trải nghiệm với các công cụ xây dựng Front-End: Webpack, Yarn, Gulp.\n•	Kiến thức về DOM, Ajax, JSON, Dịch vụ web, API Web, API Restful, xác thực dựa trên mã thông báo.\n•	Quen thuộc với các công cụ phát triển và gỡ lỗi cho các vấn đề đa nền tảng, trình duyệt chéo.\n•	Có kinh nghiệm Web socket/ Socket.io/ JavaScript không đồng bộ.\n•	Hiểu biết và thành thạo các công cụ Devops như Jenkins, Git,... là một lợi thế.\n',0,0,'2023-05-10 04:43:16',14,1),
--        (12, NULL,NOW(),NULL,NOW(),10,'•	Trực tiếp tham gia các dự án lập trình ứng dụng di động trong ngân hàng\n•	Thực hiện (lập trình) các chức năng theo thiết kế.\n•	Cải tiến và nâng cao chất lượng dự án, đề xuất ra các giải pháp kỹ thuật giải quyết các vấn đề phát sinh.\n•	Tham gia xây dựng, đóng góp nhằm cải thiện và tối ưu trải nghiệm người dùng.\n•	Làm việc với RESTful API để kết nối ứng dụng với server\n•	Các công việc khác thuộc chuyên môn theo sự phân công của cấp trên.\n','2023-05-31 04:43:16','Tòa nhà LPBank, số 210 Trần Quang Khải, Phường Tràng Tiền, Quận Hoàn Kiếm, Thành phố Hà Nội','Lập trình viên Mobile Android','•	Thưởng các Ngày lễ, Tết theo chính sách ngân hàng từng thời kỳ (Từ 16-18 tháng lương/ năm)\n•	Đầy đủ các chế độ, quyền lợi của cán bộ nhân viên Ngân hàng.\n•	Môi trường năng động, thân thiện, gần gũi. Có nhiều cơ hội học đào tạo, học hỏi và phát triển.\n•	Chính sách review lương hàng năm\n•	Cung cấp thiết bị làm việc\n•	Du lịch/team building hằng năm\n•	Tham gia đầy đủ bảo hiểm (BHXH/BHYT)\n•	12 ngày phép năm\n•	Làm việc từ 08h00 đến 17h00, từ Thứ 2 đến Thứ 6 hàng tuần. Từ 08h00 đến 12h00 sáng Thứ 7\n\n','•	Học vấn: Tốt nghiệp Cao đẳng/Đại học các ngành về Công nghệ thông tin hoặc các ngành liên quan khác.\n•	Kinh nghiệm: Có ít nhất 1 năm kinh nghiệm trong phát triển ứng dụng Android\n•	Nắm vững kiến thức về Java, Xml, Json, Android SDK\n•	Biết thêm Kotlin/Flutter là một lợi thế\n•	Hiểu và làm việc được với các mô hình OOP, MVP, MVVM\n•	Có kinh nghiệm làm việc với Firebase Message, socket\n•	Có kiến thức về hệ quản trị cơ sở dữ liệu SQL\n•	Kỹ năng mềm: Giao tiếp, làm việc độc lập/nhóm, tự học và nghiên cứu,...\n•	Thái độ, tinh thần, tư duy: Tiên phong, cầu tiến, chủ động, tuân thủ quy định, trung thực, thẳng thắn, biết lắng nghe, có tinh thần trách nhiệm cao, luôn hướng đến giải pháp,...\n•	Ngôn ngữ: Tiếng Anh khá trở lên, có khả năng đọc hiểu các tài liệu tiếng anh chuyên ngành.\n',35000000,14000000,'2023-05-22 04:43:16',15,1),
--        (13, NULL,NOW(),NULL,NOW(),3,'•	Participate in analyzing, designing, and improving the functions of the company\'s products and services.\n•	Coordinate with the leader and team to build mobile apps by Flutter, Android, IOS native. \n•	Participate in operating and maintaining apps.\n•	Research new technologies suitable for investment projects of the company.\n•	Other jobs when assigned by superiors.\n','2023-05-30 04:43:16','Tầng 2, Tòa nhà Thái Sơn, 153 Ung Văn Khiêm, Phường 25, Quận Bình Thạnh, Thành phố Hồ Chí Minh','Mobile Developer (Flutter)','•	Good salary, bonus for 13 months and according to the project\n•	Have the opportunity to face many problems in programming and life that a big company you never have.\n•	Many opportunities to learn, demonstrate ability and advance at work.\n•	Improve English by working and daily meeting.\n•	Being trained if not experienced\n•	Working with young, healthy, ambitious and capable people.\n•	Open, dynamic, colorful environment.\n•	All regimes as prescribed by the State (health insurance, social insurance, ...)\n•	In case of emergency (COVID-19), our company will flexible support candidates for online interview\n•	Mon - Fri\n','•	Have 1 - 2 years of experience coding Flutter.\n•	Experience working with Bloc/RxDart.\n•	Know some design patterns (singleton, factory, data repository..).\n•	Enthusiasm for technology with a pulse on current trends and technologies in the area of mobile application development.\n•	Experience with Android (kotlin) or IOS (swift)  is a plus.\n•	Experience with and understanding of test-driven design and unit testing is a plus.\n•	Agile/Scrum experience is a plus.\n\n',0,0,'2023-05-22 04:43:16',16,1),
--        (14, NULL,NOW(),NULL,NOW(),5,'UC10','2025-08-10 00:00:00','50 Phạm Văn Chiêu, Thành phố Hồ Chí Minh','Fresher java','Trợ cấp thực tập: 3.000.000 - 5.000.000 đồng/tháng. \\r\\nLàm việc cùng team tech trẻ trung, đầy nhiệt huyết và năng động. \\r\\nCơ hội học hỏi và làm việc trực tiếp cùng các Leader đầy kinh nghiệm.','UC10',5000000,1000000,'2023-05-29 10:51:10',16,1),
--        (15, NULL,NOW(),NULL,NOW(),7,'UC11','2025-08-11 00:00:00','50 Kha Vạn Cân, Hà Nội','Intern Java','Cơ hội làm việc với một môi trường chuyên nghiệp.','UC11',3000000,1000000,'2023-05-29 10:51:10',12,1),
--        (16, NULL,NOW(),NULL,NOW(),2,'UC12','2025-08-12 00:00:00','50 Kha Vạn Cân, Hà Nội','Intern Flutter','Tham gia vào các dự án thiết kế, phát triển các sản phẩm mới theo yêu cầu của khách hàng hoặc từ Leader.','UC12',2500000,1000000,'2023-05-29 10:51:10',3,1),
--        (17, NULL,NOW(),NULL,NOW(),6,'UC13','2025-08-13 00:00:00','50 Kha Vạn Cân, Hà Nội','Frontend','Tham gia vào các dự án thiết kế, phát triển các sản phẩm mới theo yêu cầu của khách hàng hoặc từ Leader.','UC13',3000000,1000000,'2023-05-29 10:51:10',3,1),
--        (18, NULL,NOW(),NULL,NOW(),5,'UC14','2025-08-14 00:00:00','268 Lý Thường Kiệt, Thành phố Hồ Chí Minh','Tester','Cơ hội làm việc với một môi trường chuyên nghiệp.\n-JGHAX','UC14',4000000,1000000,'2023-05-29 10:51:10',3,1),
--        (19, NULL,NOW(),NULL,NOW(),5,'UC10','2021-12-31 00:00:00','50 Phạm Văn Chiêu, Thành phố Hồ Chí Minh','Fresher java','Trợ cấp thực tập: 3.000.000 - 5.000.000 đồng/tháng. \\r\\nLàm việc cùng team tech trẻ trung, đầy nhiệt huyết và năng động. \\r\\nCơ hội học hỏi và làm việc trực tiếp cùng các Leader đầy kinh nghiệm.','UC10',5000000,1000000,'2023-05-29 14:21:01',18,1),
--        (20, NULL,NOW(),NULL,NOW(),7,'UC11','2025-08-11 00:00:00','50 Kha Vạn Cân, Hà Nội','Intern Java','Cơ hội làm việc với một môi trường chuyên nghiệp.','UC11',3000000,1000000,NOW(),1,1),
--        (21, NULL,NOW(),NULL,NOW(),2,'UC12','2025-08-12 00:00:00','50 Kha Vạn Cân, Hà Nội','Intern Flutter','Tham gia vào các dự án thiết kế, phát triển các sản phẩm mới theo yêu cầu của khách hàng hoặc từ Leader.','UC12',2500000,1000000,NOW(),4,1),
--        (22, NULL,NOW(),NULL,NOW(),6,'UC13','2025-08-13 00:00:00','50 Kha Vạn Cân, Hà Nội','Frontend','Tham gia vào các dự án thiết kế, phát triển các sản phẩm mới theo yêu cầu của khách hàng hoặc từ Leader.','UC13',3000000,1000000,NOW(),5,1),
--        (23, NULL,NOW(),NULL,NOW(),5,'UC14','2025-08-14 00:00:00','268 Lý Thường Kiệt, Thành phố Hồ Chí Minh','Tester','Cơ hội làm việc với một môi trường chuyên nghiệp.\n-JGHAX','UC14',4000000,1000000,NOW(),1,1),
--        (24, NULL,NOW(),NULL,NOW(),12,'BACK END','2023-07-25 00:00:00','phan van tri','Thực tập sinh JAVA','Lương: 30.000.000 - 50.000.000 đồng/tháng. \r\nLàm việc cùng team tech trẻ trung, đầy nhiệt huyết và năng động. \r\nCơ hội học hỏi và làm việc trực tiếp cùng các Leader đầy kinh nghiệm.','Có tối thiểu 2 tháng làm việc với JAVA',20023400,10012400,'2023-04-15 00:00:00',1,1);
--
-- -- 8. Job major
-- INSERT INTO `job_major`(`job_id`, `major_id`)
-- SELECT 1, 4 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 1 AND `major_id` = 4)
-- UNION
-- SELECT 1, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 1 AND `major_id` = 3)
-- UNION
-- SELECT 2, 4 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 2 AND `major_id` = 4)
-- UNION
-- SELECT 2, 6 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 2 AND `major_id` = 6)
-- UNION
-- SELECT 2, 1 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 2 AND `major_id` = 1)
-- UNION
-- SELECT 3, 2 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 3 AND `major_id` = 2)
-- UNION
-- SELECT 3, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 3 AND `major_id` = 3)
-- UNION
-- SELECT 3, 4 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 3 AND `major_id` = 4)
-- UNION
-- SELECT 5, 6 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 5 AND `major_id` = 6)
-- UNION
-- SELECT 5, 1 WHERE NOT EXISTS (SELECT 1 FROM `job_major` WHERE `job_id` = 5 AND `major_id` = 1);
--
-- -- 9. Job position
-- INSERT INTO `job_position`(`job_id`, `position_id`)
-- SELECT 1, 1 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 1 AND `position_id` = 1)
-- UNION
-- SELECT 1, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 1 AND `position_id` = 3)
-- UNION
-- SELECT 4, 1 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 4 AND `position_id` = 1)
-- UNION
-- SELECT 4, 2 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 4 AND `position_id` = 2)
-- UNION
-- SELECT 2, 1 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 2 AND `position_id` = 1)
-- UNION
-- SELECT 3, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 3 AND `position_id` = 3)
-- UNION
-- SELECT 3, 7 WHERE NOT EXISTS (SELECT 1 FROM `job_position` WHERE `job_id` = 3 AND `position_id` = 7);
--
-- -- 10. Job schedule
-- INSERT INTO `job_schedule`(`job_id`, `schedule_id`)
-- SELECT 1, 2 WHERE NOT EXISTS (SELECT 1 FROM `job_schedule` WHERE `job_id` = 1 AND `schedule_id` = 2)
-- UNION
-- SELECT 1, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_schedule` WHERE `job_id` = 1 AND `schedule_id` = 3)
-- UNION
-- SELECT 1, 1 WHERE NOT EXISTS (SELECT 1 FROM `job_schedule` WHERE `job_id` = 1 AND `schedule_id` = 1)
-- UNION
-- SELECT 4, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_schedule` WHERE `job_id` = 4 AND `schedule_id` = 3)
-- UNION
-- SELECT 10, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_schedule` WHERE `job_id` = 10 AND `schedule_id` = 3)
-- UNION
-- SELECT 2, 3 WHERE NOT EXISTS (SELECT 1 FROM `job_schedule` WHERE `job_id` = 2 AND `schedule_id` = 3);