package com.r2s.findInternship.domain.constant;

public class Constant {
    public static final String DATE_FORMAT = "dd-MM-yyyy";
    public static final String DATE_TIME_FORMAT = DATE_FORMAT + " HH:mm:ss";
    public static final String API = "api";
    public static final String ADMIN = "/admin";
    public static final String APPLICATION = "-application";
    public static final String CANDIDATE = "/candidate";
    public static final String COMPANY = "/company";
    public static final String COUNTRY = "/country";
    public static final String DEMAND = "-demand";
    public static final String INTERNSHIP = "/internship";
    public static final String RECRUITMENT = "-recruitment";
    public static final String PROGRAMME = "-programme";
    public static final String DISTRICT = "/district";
    public static final String GENERAL = "-general";
    public static final String HR = "/hr";
    public static final String SAVE_CANDIDATE = "/save-candidate";
    public static final String SAVE_INTERNSHIP_PROGRAMME = "/save-internship-programme";
    public static final String JOB = "/job";
    public static final String JOB_POSITION = "/job-position";
    public static final String POSITION = "/position";
    public static final String JOB_CARE = "-job-care";
    public static final String LOCATION = "/location";
    public static final String LOGIN = "/login";
    public static final String MAIL = "/mail";
    public static final String MAJOR = "/major";
    public static final String SCHEDULE = "/schedule";
    public static final String PROVINCE = "/province";
    public static final String STATISTICS = "/statistics";
    public static final String PARTNER = "/partner";
    public static final String RATE = "-rate";
    public static final String ROLE = "/role";
    public static final String STATUS = "/status";
    public static final String USER = "/user";
    public static final String UNIVERSITY = "/university";
    public static final String FILE = "/file";
    public static final String JWT_SECRET = "4fH6y0cy28gSXLcbTyAeR12JfxEKK2R/aU7/7IYRQdE=";
    public static final String LOGOUT = "/logout";
    public static final String ACTIVE = "/active";
}